version: '2.1'

services:
  mender-useradm:
    image: mendersoftware/useradm:mender-3.7.0
    command: server --automigrate
    volumes:
      - ./keys/useradm/private.key:/etc/useradm/rsa/private.pem
    environment:
      USERADM_SERVER_PRIV_KEY_PATH: /etc/useradm/rsa/private.pem
      MONGO_URL: mongodb://mender-mongo:27017
    networks:
      - mender

  mender-device-auth:
    image: mendersoftware/deviceauth:mender-3.7.0
    command: server --automigrate
    volumes:
      - ./keys/deviceauth/private.key:/etc/deviceauth/rsa/private.pem
    environment:
      DEVICEAUTH_SERVER_PRIV_KEY_PATH: /etc/deviceauth/rsa/private.pem
      MONGO_URL: mongodb://mender-mongo:27017
    networks:
      - mender

  mender-inventory:
    image: mendersoftware/inventory:mender-3.7.0
    command: server --automigrate
    environment:
      MONGO_URL: mongodb://mender-mongo:27017
    networks:
      - mender

  mender-deployments:
    image: mendersoftware/deployments:mender-3.7.0
    command: server --automigrate
    volumes:
      - ./cert/cert.crt:/etc/ssl/certs/docker.mender.io.crt
    environment:
      STORAGE_BACKEND_CERT: /etc/ssl/certs/docker.mender.io.crt
      DEPLOYMENTS_AWS_AUTH_KEY: minio
      DEPLOYMENTS_AWS_AUTH_SECRET: minio123
      DEPLOYMENTS_AWS_URI: http://minio:9000
      DEPLOYMENTS_AWS_EXTERNAL_URI: https://s3.docker.mender.io
      DEPLOYMENTS_STORAGE_BUCKET: mender-artifact-storage
      MONGO_URL: mongodb://mender-mongo:27017
    depends_on:
      - mender-mongo
    networks:
      - mender

  mender-api-gateway:
    image: traefik:v2.2
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command:
      - --accesslog=true
      - --api.dashboard=true
      - --api.insecure=true
      - --entrypoints.http.address=:80
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.https.address=:443
      - --entryPoints.https.transport.respondingTimeouts.idleTimeout=7200
      - --entryPoints.https.transport.respondingTimeouts.readTimeout=7200
      - --entryPoints.https.transport.respondingTimeouts.writeTimeout=7200
      - --log.level=DEBUG
      - --ping=true
      - --providers.file.directory=/etc/traefik/config
    environment:
      MENDER_DEMO: "true"
      TRAEFIK_API: "true"
    networks:
      mender:
        aliases:
          - docker.mender.io
          - s3.docker.mender.io
    volumes:
      - ./config/traefik/traefik.tls.yaml:/etc/traefik/config/traefik.tls.yaml:ro
      - ./cert/cert.crt:/etc/traefik/certs/cert.crt
      - ./cert/private.key:/etc/traefik/certs/private.key

  mender-gui:
    image: mendersoftware/gui:mender-3.7.0
    environment:
      DEMO: "true"
    networks:
      - mender

  minio:
    image: minio/minio:latest
    command: server /export
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - minio-data:/export
    networks:
      mender:
        aliases:
          - minio

  mender-mongo:
    image: mongo:4.4
    volumes:
      - mender-mongo-db:/data/db
    networks:
      - mender

volumes:
  mender-mongo-db:
  minio-data:

networks:
  mender:
